### ISSUE TITLE
调试时无法返回回调地址

### ISSUE THREAD

**Issue by Rlyehzoo** [doubaniux/boofilsic#103]
菜鸟请教，部署网站时，登录跳转会出现The redirect uri included is not valid。请问原因是什么呢？是因为返回的是本地的地址吗？请问怎样做才能顺利调试呢？
出现`The redirect uri included is not valid.`时的地址是
https://o3o.ca/oauth/authorize?client_id=pLEr3UrXgD_LfYsRL0SDTK2wxrvvvzBiWPNAH1kE1Lk&scope=read%20write%20follow&redirect_uri=http://127.0.0.1:8000/users/OAuth2_login/&response_type=code

**Comment by doubaniux** [comment]
@Rlyehzoo Hello, please make sure you have correctly set the redirect URIs on your mastodon site. Like what @joseph-cheung mentioned, pay attention to the different redirect URIs under debug mode.
