### ISSUE TITLE
上传过程中不小心把上传文件挪走了，上传进度卡主了，导入的button 也不能点击

### ISSUE THREAD

**Issue by onestarshang** [doubaniux/boofilsic#107]
![image](https://user-images.githubusercontent.com/5790662/145563180-29b70144-f645-450b-bc18-56c9429f7e00.png)

**Comment by haozii** [comment]
选好文件后一直挂着好了，我最近卡了几个小时，然后就干脆挂机一晚上，第二天早上就好了

**Comment by doubaniux** [comment]
@onestarshang Hi, please contact your webmaster (of NeoDB I guess?) in such case. Will consider this edge case in the future, thanks for reporting it.

**Comment by doubaniux** [comment]
> 选好文件后一直挂着好了，我最近卡了几个小时，然后就干脆挂机一晚上，第二天早上就好了

Hello, there is no need to keep the page open, the task runs back in the server.
