### ISSUE TITLE
搜索音乐条目之后，如果是bandcamp的，无法标记，点击条目之后显示爬取数据失败

### ISSUE THREAD

**Issue by onestarshang** [doubaniux/boofilsic#113]
搜索音乐条目之后，如果是bandcamp的，无法标记，点击条目之后显示爬取数据失败

**Comment by doubaniux** [comment]
@onestarshang Hello, this feature is currently not integrated into NiceDB, it is normal that items from bandcamp cannot be scraped. However, there is a plan for that in the near future.
