### ISSUE TITLE
[Bug] 书籍简介换行问题

### ISSUE THREAD

**Issue by umonaca** [doubaniux/boofilsic#25]
可能是被什么strip掉了

**Comment by doubaniux** [comment]
on which page?

**Comment by umonaca** [comment]
All of them. Example: https://nicedb.org/books/92/

**Comment by umonaca** [comment]
No this commit did not fix the bug.
When you add a book with line breakers in description, the line breakers are stripped out after submission.

**Comment by doubaniux** [comment]
@umonaca No nothing is stripped, everything is stored just as it should be, the problem is how to render. Continuous white spaces will collapse and this is how html works. But if visible indent of lines is what you want, it can be implemented in the future.
