### ISSUE TITLE
[Feature] 添加条目前检查是否已有条目

### ISSUE THREAD

**Issue by Gnothi-Seauton** [doubaniux/boofilsic#51]
有的书和影有两个条目，但两个条目实际上指向了同一个ISBN号或同一部电影，我想豆瓣要求ISBN和imdb码也是因为这个
例如：https://nicedb.org/books/800/   https://nicedb.org/books/215/
还有ISBN-10和ISBN-13造成的两个条目，例如：https://nicedb.org/books/21/   https://nicedb.org/books/174/  （其实红太阳确实有另一本简体版的书）
电影的例子：https://nicedb.org/movies/13/   https://nicedb.org/movies/69/

**Comment by doubaniux** [comment]
Now every item has an unique identifier, the source url.
