### ISSUE TITLE
[Bug] 500错误

### ISSUE THREAD

**Issue by umonaca** [doubaniux/boofilsic#68]
复现方法：
使用我在里瓣（而不是J站）的账号登录NiceDB，然后打开https://nicedb.org/users/melonpan404@jabberwocky.moe/
即出现500错误

**Comment by doubaniux** [comment]
I manually added this user's cross site id in donotban.com then the problem solved, I assume this is caused by the unreliable mastodon search api https://github.com/doubaniux/boofilsic/blob/master/mastodon/api.py#L115
