### ISSUE TITLE
无法上传豆伴备份

### ISSUE THREAD

**Issue by changyeli** [doubaniux/boofilsic#95]
<img width="381" alt="Screen Shot" src="https://user-images.githubusercontent.com/9058204/133477294-3fe4143e-8e32-4908-8a45-a3e6fdd13c53.png">
如图，如果取消覆盖原有标记的话也是这样，一直停在0%这里不动

**Comment by Guanchishan** [comment]
似乎修复了，现在我的正在上传中。之前也碰到和你一样问题。

**Comment by doubaniux** [comment]
It seems more of a problem of deployment or maintenance, please contact the web admin to solve these kind of issues.
